# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "bundler" # パッケージ種別
    directory: "/" # パッケージが存在するディレクトリ
    target-branch: "develop" # PRを送るブランチ
    reviewers: # レビュアー
      - "prum-jp/musashino_reference-check"
    schedule: # 更新のスケジュール
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: Asia/Tokyo
    groups: # PRをまとめる条件
      dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "bundler更新: "
  - package-ecosystem: docker
    directory: "/"
    target-branch: "develop"
    reviewers:
      - "prum-jp/musashino_reference-check"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: Asia/Tokyo
    groups:
      dependencies:
        patterns:
          - "*"
    commit-message:
      prefix: "Docker更新: "
